export const API_ENDPOINTS = {
  PRODUCTS: '/api/products.json',
  PRODUCTS_2: '/api/products_2.json',
  CATEGORIES: '/api/categories.json',
  CATEGORIES_2: '/api/categories_2.json',
  CATEGORIES_ANCIENT: '/api/categories_ancient.json',
  FEATURED_CATEGORIES: '/api/featured_categories.json',
  FLASH_SALE_PRODUCTS: '/api/products_flash_sale.json',
  FLASH_SALE_PRODUCTS_ANCIENT: '/api/products_flash_sale_ancient.json',
  FEATURED_PRODUCTS: '/api/featured_products.json',
  FEATURED_PRODUCTS_ANCIENT: '/api/featured_products_ancient.json',
  ON_SELLING_PRODUCTS: '/api/products_on_selling.json',
  NEW_ARRIVAL_PRODUCTS: '/api/products_new_arrival.json',
  NEW_ARRIVAL_PRODUCTS_ANCIENT: '/api/products_ancient.json',
  BRANDS: '/api/brands.json',
  BRANDS_ANCIENT: '/api/brands_ancient.json',
  BEST_SELLER_PRODUCTS: '/api/products_best_seller.json',
  TOP_SELLER_PRODUCTS: '/api/products_top_seller.json',
  POPULAR_PRODUCTS: '/api/products_popular.json',
  RELATED_PRODUCTS: '/api/related_products.json',
  PRODUCT: '/api/product.json',
  COLLECTIONS: '/api/collections.json',
  ORDER: '/api/order.json',
  ORDERS: '/api/orders.json',
  CREATE_ORDERS: '/api/create-order',
  CREATE_CART: '/api/cart', // New cart endpoint
  SHOPS: '/api/shops.json',
  SHOP: '/api/shop.json',
  USERS_ME: '/api/me',
  NEWS_LETTER_CONFIRM: '/api/newsletter/confirm',
  SIGNUP: '/api/register.json',
  LOGIN: '/api/login',
  PUROHITS: '/api/purohits.json'
};
