export const megaMenuData = [
  {
    id: 1,
    path: "/search?q=e-books",
    label: "E-Books",
    data: {
      _id: "68abe10278f44bb56eb0a562",
      name: "E-Books",
      slug: "e-books",
      parentId: null,
      isLeaf: false,
      isActive: true,
      displayOrder: 1,
      attributes: [],
      path: [
        {
          id: "68abe10278f44bb56eb0a562",
          slug: "e-books",
          name: "E-Books",
        },
      ],
      level: 1,
      fullSlug: "e-books",
      code: "CAT-1-e-books-fplzQj",
      createdAt: "2025-08-25T04:05:22.516Z",
      updatedAt: "2025-08-25T04:05:22.516Z",
      __v: 0,
    },
    columns: [],
  },
  {
    id: 2,
    path: "/search?q=clothing",
    label: "Clothing",
    data: {
      _id: "68ab11a11cd8ac2fa2b71e8c",
      name: "Clothing",
      slug: "clothing",
      parentId: null,
      isLeaf: false,
      isActive: true,
      displayOrder: 2,
      attributes: [],
      path: [
        {
          id: "68ab11a11cd8ac2fa2b71e8c",
          slug: "clothing",
          name: "Clothing",
        },
      ],
      level: 1,
      fullSlug: "clothing",
      code: "CAT-1-clothing-oJ-i-b",
      createdAt: "2025-08-24T13:20:33.959Z",
      updatedAt: "2025-08-24T13:20:35.118Z",
      __v: 0,
    },
    columns: [
      {
        id: 1,
        columnItems: [
          {
            id: 1,
            path: "/search?q=clothing/men",
            label: "Men",
            data: {
              _id: "68ab11a21cd8ac2fa2b71e9b",
              name: "Men",
              slug: "men",
              parentId: "68ab11a11cd8ac2fa2b71e8c",
              isLeaf: false,
              isActive: true,
              displayOrder: 1,
              attributes: [],
              path: [
                {
                  id: "68ab11a11cd8ac2fa2b71e8c",
                  slug: "clothing",
                  name: "Clothing",
                },
                {
                  id: "68ab11a21cd8ac2fa2b71e9b",
                  slug: "men",
                  name: "Men",
                },
              ],
              level: 2,
              fullSlug: "clothing/men",
              code: "CAT-2-men-pwRHAw",
              createdAt: "2025-08-24T13:20:34.638Z",
              updatedAt: "2025-08-24T13:20:37.457Z",
              __v: 0,
            },
            columnItemItems: [
              {
                id: 1,
                path: "/search?q=clothing/men/men-formal",
                label: "Formal",
                data: {
                  _id: "68ab11a41cd8ac2fa2b71ed9",
                  name: "Formal",
                  slug: "men-formal",
                  parentId: "68ab11a21cd8ac2fa2b71e9b",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 1,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a11cd8ac2fa2b71e8c",
                      slug: "clothing",
                      name: "Clothing",
                    },
                    {
                      id: "68ab11a21cd8ac2fa2b71e9b",
                      slug: "men",
                      name: "Men",
                    },
                    {
                      id: "68ab11a41cd8ac2fa2b71ed9",
                      slug: "men-formal",
                      name: "Formal",
                    },
                  ],
                  level: 3,
                  fullSlug: "clothing/men/men-formal",
                  code: "CAT-3-men-formal-3G_Zv1",
                  createdAt: "2025-08-24T13:20:36.639Z",
                  updatedAt: "2025-08-24T13:20:36.639Z",
                  __v: 0,
                },
              },
              {
                id: 2,
                path: "/search?q=clothing/men/men-semi-formal",
                label: "Semi Formal",
                data: {
                  _id: "68ab11a41cd8ac2fa2b71ede",
                  name: "Semi Formal",
                  slug: "men-semi-formal",
                  parentId: "68ab11a21cd8ac2fa2b71e9b",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 2,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a11cd8ac2fa2b71e8c",
                      slug: "clothing",
                      name: "Clothing",
                    },
                    {
                      id: "68ab11a21cd8ac2fa2b71e9b",
                      slug: "men",
                      name: "Men",
                    },
                    {
                      id: "68ab11a41cd8ac2fa2b71ede",
                      slug: "men-semi-formal",
                      name: "Semi Formal",
                    },
                  ],
                  level: 3,
                  fullSlug: "clothing/men/men-semi-formal",
                  code: "CAT-3-men-semi-formal-oTnar-",
                  createdAt: "2025-08-24T13:20:36.818Z",
                  updatedAt: "2025-08-24T13:20:36.818Z",
                  __v: 0,
                },
              },
              {
                id: 3,
                path: "/search?q=clothing/men/men-festival",
                label: "Festival",
                data: {
                  _id: "68ab11a41cd8ac2fa2b71ee3",
                  name: "Festival",
                  slug: "men-festival",
                  parentId: "68ab11a21cd8ac2fa2b71e9b",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 3,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a11cd8ac2fa2b71e8c",
                      slug: "clothing",
                      name: "Clothing",
                    },
                    {
                      id: "68ab11a21cd8ac2fa2b71e9b",
                      slug: "men",
                      name: "Men",
                    },
                    {
                      id: "68ab11a41cd8ac2fa2b71ee3",
                      slug: "men-festival",
                      name: "Festival",
                    },
                  ],
                  level: 3,
                  fullSlug: "clothing/men/men-festival",
                  code: "CAT-3-men-festival-SoJSsX",
                  createdAt: "2025-08-24T13:20:36.959Z",
                  updatedAt: "2025-08-24T13:20:36.959Z",
                  __v: 0,
                },
              },
              {
                id: 4,
                path: "/search?q=clothing/men/groom",
                label: "Groom",
                data: {
                  _id: "68ab11a51cd8ac2fa2b71ee8",
                  name: "Groom",
                  slug: "groom",
                  parentId: "68ab11a21cd8ac2fa2b71e9b",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 4,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a11cd8ac2fa2b71e8c",
                      slug: "clothing",
                      name: "Clothing",
                    },
                    {
                      id: "68ab11a21cd8ac2fa2b71e9b",
                      slug: "men",
                      name: "Men",
                    },
                    {
                      id: "68ab11a51cd8ac2fa2b71ee8",
                      slug: "groom",
                      name: "Groom",
                    },
                  ],
                  level: 3,
                  fullSlug: "clothing/men/groom",
                  code: "CAT-3-groom-na9Fr9",
                  createdAt: "2025-08-24T13:20:37.258Z",
                  updatedAt: "2025-08-24T13:20:37.258Z",
                  __v: 0,
                },
              },
              {
                id: 5,
                path: "/search?q=clothing/men/men-daily-wear",
                label: "Daily Wear",
                data: {
                  _id: "68ab11a51cd8ac2fa2b71eed",
                  name: "Daily Wear",
                  slug: "men-daily-wear",
                  parentId: "68ab11a21cd8ac2fa2b71e9b",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 5,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a11cd8ac2fa2b71e8c",
                      slug: "clothing",
                      name: "Clothing",
                    },
                    {
                      id: "68ab11a21cd8ac2fa2b71e9b",
                      slug: "men",
                      name: "Men",
                    },
                    {
                      id: "68ab11a51cd8ac2fa2b71eed",
                      slug: "men-daily-wear",
                      name: "Daily Wear",
                    },
                  ],
                  level: 3,
                  fullSlug: "clothing/men/men-daily-wear",
                  code: "CAT-3-men-daily-wear-Brc6La",
                  createdAt: "2025-08-24T13:20:37.398Z",
                  updatedAt: "2025-08-24T13:20:37.398Z",
                  __v: 0,
                },
              },
            ],
          },
        ],
      },
      {
        id: 2,
        columnItems: [
          {
            id: 2,
            path: "/search?q=clothing/women",
            label: "Women",
            data: {
              _id: "68ab11a21cd8ac2fa2b71ea2",
              name: "Women",
              slug: "women",
              parentId: "68ab11a11cd8ac2fa2b71e8c",
              isLeaf: false,
              isActive: true,
              displayOrder: 2,
              attributes: [],
              path: [
                {
                  id: "68ab11a11cd8ac2fa2b71e8c",
                  slug: "clothing",
                  name: "Clothing",
                },
                {
                  id: "68ab11a21cd8ac2fa2b71ea2",
                  slug: "women",
                  name: "Women",
                },
              ],
              level: 2,
              fullSlug: "clothing/women",
              code: "CAT-2-women-vUHBk4",
              createdAt: "2025-08-24T13:20:34.879Z",
              updatedAt: "2025-08-24T13:20:38.197Z",
              __v: 0,
            },
            columnItemItems: [
              {
                id: 1,
                path: "/search?q=clothing/women/women-formal",
                label: "Formal",
                data: {
                  _id: "68ab11a51cd8ac2fa2b71ef2",
                  name: "Formal",
                  slug: "women-formal",
                  parentId: "68ab11a21cd8ac2fa2b71ea2",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 1,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a11cd8ac2fa2b71e8c",
                      slug: "clothing",
                      name: "Clothing",
                    },
                    {
                      id: "68ab11a21cd8ac2fa2b71ea2",
                      slug: "women",
                      name: "Women",
                    },
                    {
                      id: "68ab11a51cd8ac2fa2b71ef2",
                      slug: "women-formal",
                      name: "Formal",
                    },
                  ],
                  level: 3,
                  fullSlug: "clothing/women/women-formal",
                  code: "CAT-3-women-formal-GlbYp_",
                  createdAt: "2025-08-24T13:20:37.538Z",
                  updatedAt: "2025-08-24T13:20:37.538Z",
                  __v: 0,
                },
              },
              {
                id: 2,
                path: "/search?q=clothing/women/women-semi-formal",
                label: "Semi Formal",
                data: {
                  _id: "68ab11a51cd8ac2fa2b71ef7",
                  name: "Semi Formal",
                  slug: "women-semi-formal",
                  parentId: "68ab11a21cd8ac2fa2b71ea2",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 2,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a11cd8ac2fa2b71e8c",
                      slug: "clothing",
                      name: "Clothing",
                    },
                    {
                      id: "68ab11a21cd8ac2fa2b71ea2",
                      slug: "women",
                      name: "Women",
                    },
                    {
                      id: "68ab11a51cd8ac2fa2b71ef7",
                      slug: "women-semi-formal",
                      name: "Semi Formal",
                    },
                  ],
                  level: 3,
                  fullSlug: "clothing/women/women-semi-formal",
                  code: "CAT-3-women-semi-formal-xhg8cx",
                  createdAt: "2025-08-24T13:20:37.658Z",
                  updatedAt: "2025-08-24T13:20:37.658Z",
                  __v: 0,
                },
              },
              {
                id: 3,
                path: "/search?q=clothing/women/women-festival",
                label: "Festival",
                data: {
                  _id: "68ab11a51cd8ac2fa2b71efc",
                  name: "Festival",
                  slug: "women-festival",
                  parentId: "68ab11a21cd8ac2fa2b71ea2",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 3,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a11cd8ac2fa2b71e8c",
                      slug: "clothing",
                      name: "Clothing",
                    },
                    {
                      id: "68ab11a21cd8ac2fa2b71ea2",
                      slug: "women",
                      name: "Women",
                    },
                    {
                      id: "68ab11a51cd8ac2fa2b71efc",
                      slug: "women-festival",
                      name: "Festival",
                    },
                  ],
                  level: 3,
                  fullSlug: "clothing/women/women-festival",
                  code: "CAT-3-women-festival-cpqTeV",
                  createdAt: "2025-08-24T13:20:37.818Z",
                  updatedAt: "2025-08-24T13:20:37.818Z",
                  __v: 0,
                },
              },
              {
                id: 4,
                path: "/search?q=clothing/women/bride",
                label: "Bride",
                data: {
                  _id: "68ab11a51cd8ac2fa2b71f01",
                  name: "Bride",
                  slug: "bride",
                  parentId: "68ab11a21cd8ac2fa2b71ea2",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 4,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a11cd8ac2fa2b71e8c",
                      slug: "clothing",
                      name: "Clothing",
                    },
                    {
                      id: "68ab11a21cd8ac2fa2b71ea2",
                      slug: "women",
                      name: "Women",
                    },
                    {
                      id: "68ab11a51cd8ac2fa2b71f01",
                      slug: "bride",
                      name: "Bride",
                    },
                  ],
                  level: 3,
                  fullSlug: "clothing/women/bride",
                  code: "CAT-3-bride-iVIXvQ",
                  createdAt: "2025-08-24T13:20:37.958Z",
                  updatedAt: "2025-08-24T13:20:37.958Z",
                  __v: 0,
                },
              },
              {
                id: 5,
                path: "/search?q=clothing/women/women-daily-wear",
                label: "Daily Wear",
                data: {
                  _id: "68ab11a61cd8ac2fa2b71f06",
                  name: "Daily Wear",
                  slug: "women-daily-wear",
                  parentId: "68ab11a21cd8ac2fa2b71ea2",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 5,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a11cd8ac2fa2b71e8c",
                      slug: "clothing",
                      name: "Clothing",
                    },
                    {
                      id: "68ab11a21cd8ac2fa2b71ea2",
                      slug: "women",
                      name: "Women",
                    },
                    {
                      id: "68ab11a61cd8ac2fa2b71f06",
                      slug: "women-daily-wear",
                      name: "Daily Wear",
                    },
                  ],
                  level: 3,
                  fullSlug: "clothing/women/women-daily-wear",
                  code: "CAT-3-women-daily-wear-8rYYx-",
                  createdAt: "2025-08-24T13:20:38.138Z",
                  updatedAt: "2025-08-24T13:20:38.138Z",
                  __v: 0,
                },
              },
            ],
          },
        ],
      },
      {
        id: 3,
        columnItems: [
          {
            id: 3,
            path: "/search?q=clothing/kids",
            label: "Kids",
            data: {
              _id: "68ab11a21cd8ac2fa2b71ea7",
              name: "Kids",
              slug: "kids",
              parentId: "68ab11a11cd8ac2fa2b71e8c",
              isLeaf: false,
              isActive: true,
              displayOrder: 3,
              attributes: [],
              path: [
                {
                  id: "68ab11a11cd8ac2fa2b71e8c",
                  slug: "clothing",
                  name: "Clothing",
                },
                {
                  id: "68ab11a21cd8ac2fa2b71ea7",
                  slug: "kids",
                  name: "Kids",
                },
              ],
              level: 2,
              fullSlug: "clothing/kids",
              code: "CAT-2-kids-k6Y-P0",
              createdAt: "2025-08-24T13:20:35.059Z",
              updatedAt: "2025-08-24T13:20:38.557Z",
              __v: 0,
            },
            columnItemItems: [
              {
                id: 1,
                path: "/search?q=clothing/kids/boy",
                label: "Boy",
                data: {
                  _id: "68ab11a61cd8ac2fa2b71f0b",
                  name: "Boy",
                  slug: "boy",
                  parentId: "68ab11a21cd8ac2fa2b71ea7",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 1,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a11cd8ac2fa2b71e8c",
                      slug: "clothing",
                      name: "Clothing",
                    },
                    {
                      id: "68ab11a21cd8ac2fa2b71ea7",
                      slug: "kids",
                      name: "Kids",
                    },
                    {
                      id: "68ab11a61cd8ac2fa2b71f0b",
                      slug: "boy",
                      name: "Boy",
                    },
                  ],
                  level: 3,
                  fullSlug: "clothing/kids/boy",
                  code: "CAT-3-boy-WhAMCy",
                  createdAt: "2025-08-24T13:20:38.279Z",
                  updatedAt: "2025-08-24T13:20:40.697Z",
                  __v: 0,
                },
                subItems: [
                  {
                    id: 1,
                    path: "/search?q=clothing/kids/boy/boy-0-2-years",
                    label: "0-2 Years",
                    data: {
                      _id: "68ab11a81cd8ac2fa2b71f38",
                      name: "0-2 Years",
                      slug: "boy-0-2-years",
                      parentId: "68ab11a61cd8ac2fa2b71f0b",
                      isLeaf: false,
                      isActive: true,
                      displayOrder: 1,
                      attributes: [],
                      path: [
                        {
                          id: "68ab11a11cd8ac2fa2b71e8c",
                          slug: "clothing",
                          name: "Clothing",
                        },
                        {
                          id: "68ab11a21cd8ac2fa2b71ea7",
                          slug: "kids",
                          name: "Kids",
                        },
                        {
                          id: "68ab11a61cd8ac2fa2b71f0b",
                          slug: "boy",
                          name: "Boy",
                        },
                        {
                          id: "68ab11a81cd8ac2fa2b71f38",
                          slug: "boy-0-2-years",
                          name: "0-2 Years",
                        },
                      ],
                      level: 4,
                      fullSlug: "clothing/kids/boy/boy-0-2-years",
                      code: "CAT-4-boy-0-2-years-Gv0I6C",
                      createdAt: "2025-08-24T13:20:40.298Z",
                      updatedAt: "2025-08-24T13:20:41.917Z",
                      __v: 0,
                    },
                    nestedItems: [
                      {
                        id: 1,
                        path: "/search?q=clothing/kids/boy/boy-0-2-years/boy-0-2-traditional",
                        label: "Traditional",
                        data: {
                          _id: "68ab11a91cd8ac2fa2b71f56",
                          name: "Traditional",
                          slug: "boy-0-2-traditional",
                          parentId: "68ab11a81cd8ac2fa2b71f38",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 1,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f0b",
                              slug: "boy",
                              name: "Boy",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f38",
                              slug: "boy-0-2-years",
                              name: "0-2 Years",
                            },
                            {
                              id: "68ab11a91cd8ac2fa2b71f56",
                              slug: "boy-0-2-traditional",
                              name: "Traditional",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/boy/boy-0-2-years/boy-0-2-traditional",
                          code: "CAT-5-boy-0-2-traditional-Ue9her",
                          createdAt: "2025-08-24T13:20:41.359Z",
                          updatedAt: "2025-08-24T13:20:41.359Z",
                          __v: 0,
                        },
                      },
                      {
                        id: 2,
                        path: "/search?q=clothing/kids/boy/boy-0-2-years/boy-0-2-daily-wear",
                        label: "Daily Wear",
                        data: {
                          _id: "68ab11a91cd8ac2fa2b71f5b",
                          name: "Daily Wear",
                          slug: "boy-0-2-daily-wear",
                          parentId: "68ab11a81cd8ac2fa2b71f38",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 2,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f0b",
                              slug: "boy",
                              name: "Boy",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f38",
                              slug: "boy-0-2-years",
                              name: "0-2 Years",
                            },
                            {
                              id: "68ab11a91cd8ac2fa2b71f5b",
                              slug: "boy-0-2-daily-wear",
                              name: "Daily Wear",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/boy/boy-0-2-years/boy-0-2-daily-wear",
                          code: "CAT-5-boy-0-2-daily-wear-4E0Gm7",
                          createdAt: "2025-08-24T13:20:41.698Z",
                          updatedAt: "2025-08-24T13:20:41.698Z",
                          __v: 0,
                        },
                      },
                      {
                        id: 3,
                        path: "/search?q=clothing/kids/boy/boy-0-2-years/boy-0-2-night-wear",
                        label: "Night Wear",
                        data: {
                          _id: "68ab11a91cd8ac2fa2b71f60",
                          name: "Night Wear",
                          slug: "boy-0-2-night-wear",
                          parentId: "68ab11a81cd8ac2fa2b71f38",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 3,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f0b",
                              slug: "boy",
                              name: "Boy",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f38",
                              slug: "boy-0-2-years",
                              name: "0-2 Years",
                            },
                            {
                              id: "68ab11a91cd8ac2fa2b71f60",
                              slug: "boy-0-2-night-wear",
                              name: "Night Wear",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/boy/boy-0-2-years/boy-0-2-night-wear",
                          code: "CAT-5-boy-0-2-night-wear-kDME70",
                          createdAt: "2025-08-24T13:20:41.859Z",
                          updatedAt: "2025-08-24T13:20:41.859Z",
                          __v: 0,
                        },
                      },
                    ],
                  },
                  {
                    id: 2,
                    path: "/search?q=clothing/kids/boy/boy-2-4-years",
                    label: "2-4 Years",
                    data: {
                      _id: "68ab11a81cd8ac2fa2b71f3d",
                      name: "2-4 Years",
                      slug: "boy-2-4-years",
                      parentId: "68ab11a61cd8ac2fa2b71f0b",
                      isLeaf: false,
                      isActive: true,
                      displayOrder: 2,
                      attributes: [],
                      path: [
                        {
                          id: "68ab11a11cd8ac2fa2b71e8c",
                          slug: "clothing",
                          name: "Clothing",
                        },
                        {
                          id: "68ab11a21cd8ac2fa2b71ea7",
                          slug: "kids",
                          name: "Kids",
                        },
                        {
                          id: "68ab11a61cd8ac2fa2b71f0b",
                          slug: "boy",
                          name: "Boy",
                        },
                        {
                          id: "68ab11a81cd8ac2fa2b71f3d",
                          slug: "boy-2-4-years",
                          name: "2-4 Years",
                        },
                      ],
                      level: 4,
                      fullSlug: "clothing/kids/boy/boy-2-4-years",
                      code: "CAT-4-boy-2-4-years-raHoNi",
                      createdAt: "2025-08-24T13:20:40.458Z",
                      updatedAt: "2025-08-24T13:20:42.817Z",
                      __v: 0,
                    },
                    nestedItems: [
                      {
                        id: 1,
                        path: "/search?q=clothing/kids/boy/boy-2-4-years/boy-2-4-traditional",
                        label: "Traditional",
                        data: {
                          _id: "68ab11aa1cd8ac2fa2b71f65",
                          name: "Traditional",
                          slug: "boy-2-4-traditional",
                          parentId: "68ab11a81cd8ac2fa2b71f3d",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 1,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f0b",
                              slug: "boy",
                              name: "Boy",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f3d",
                              slug: "boy-2-4-years",
                              name: "2-4 Years",
                            },
                            {
                              id: "68ab11aa1cd8ac2fa2b71f65",
                              slug: "boy-2-4-traditional",
                              name: "Traditional",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/boy/boy-2-4-years/boy-2-4-traditional",
                          code: "CAT-5-boy-2-4-traditional-xqAcbl",
                          createdAt: "2025-08-24T13:20:42.078Z",
                          updatedAt: "2025-08-24T13:20:42.078Z",
                          __v: 0,
                        },
                      },
                      {
                        id: 2,
                        path: "/search?q=clothing/kids/boy/boy-2-4-years/boy-2-4-daily-wear",
                        label: "Daily Wear",
                        data: {
                          _id: "68ab11aa1cd8ac2fa2b71f6a",
                          name: "Daily Wear",
                          slug: "boy-2-4-daily-wear",
                          parentId: "68ab11a81cd8ac2fa2b71f3d",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 2,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f0b",
                              slug: "boy",
                              name: "Boy",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f3d",
                              slug: "boy-2-4-years",
                              name: "2-4 Years",
                            },
                            {
                              id: "68ab11aa1cd8ac2fa2b71f6a",
                              slug: "boy-2-4-daily-wear",
                              name: "Daily Wear",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/boy/boy-2-4-years/boy-2-4-daily-wear",
                          code: "CAT-5-boy-2-4-daily-wear-JZs_2I",
                          createdAt: "2025-08-24T13:20:42.378Z",
                          updatedAt: "2025-08-24T13:20:42.378Z",
                          __v: 0,
                        },
                      },
                      {
                        id: 3,
                        path: "/search?q=clothing/kids/boy/boy-2-4-years/boy-2-4-night-wear",
                        label: "Night Wear",
                        data: {
                          _id: "68ab11aa1cd8ac2fa2b71f6f",
                          name: "Night Wear",
                          slug: "boy-2-4-night-wear",
                          parentId: "68ab11a81cd8ac2fa2b71f3d",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 3,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f0b",
                              slug: "boy",
                              name: "Boy",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f3d",
                              slug: "boy-2-4-years",
                              name: "2-4 Years",
                            },
                            {
                              id: "68ab11aa1cd8ac2fa2b71f6f",
                              slug: "boy-2-4-night-wear",
                              name: "Night Wear",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/boy/boy-2-4-years/boy-2-4-night-wear",
                          code: "CAT-5-boy-2-4-night-wear-BCRFgn",
                          createdAt: "2025-08-24T13:20:42.719Z",
                          updatedAt: "2025-08-24T13:20:42.719Z",
                          __v: 0,
                        },
                      },
                    ],
                  },
                  {
                    id: 3,
                    path: "/search?q=clothing/kids/boy/boy-4-6-years",
                    label: "4-6 Years",
                    data: {
                      _id: "68ab11a81cd8ac2fa2b71f42",
                      name: "4-6 Years",
                      slug: "boy-4-6-years",
                      parentId: "68ab11a61cd8ac2fa2b71f0b",
                      isLeaf: false,
                      isActive: true,
                      displayOrder: 3,
                      attributes: [],
                      path: [
                        {
                          id: "68ab11a11cd8ac2fa2b71e8c",
                          slug: "clothing",
                          name: "Clothing",
                        },
                        {
                          id: "68ab11a21cd8ac2fa2b71ea7",
                          slug: "kids",
                          name: "Kids",
                        },
                        {
                          id: "68ab11a61cd8ac2fa2b71f0b",
                          slug: "boy",
                          name: "Boy",
                        },
                        {
                          id: "68ab11a81cd8ac2fa2b71f42",
                          slug: "boy-4-6-years",
                          name: "4-6 Years",
                        },
                      ],
                      level: 4,
                      fullSlug: "clothing/kids/boy/boy-4-6-years",
                      code: "CAT-4-boy-4-6-years-wG90BV",
                      createdAt: "2025-08-24T13:20:40.658Z",
                      updatedAt: "2025-08-24T13:20:43.337Z",
                      __v: 0,
                    },
                    nestedItems: [
                      {
                        id: 1,
                        path: "/search?q=clothing/kids/boy/boy-4-6-years/boy-4-6-traditional",
                        label: "Traditional",
                        data: {
                          _id: "68ab11aa1cd8ac2fa2b71f74",
                          name: "Traditional",
                          slug: "boy-4-6-traditional",
                          parentId: "68ab11a81cd8ac2fa2b71f42",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 1,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f0b",
                              slug: "boy",
                              name: "Boy",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f42",
                              slug: "boy-4-6-years",
                              name: "4-6 Years",
                            },
                            {
                              id: "68ab11aa1cd8ac2fa2b71f74",
                              slug: "boy-4-6-traditional",
                              name: "Traditional",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/boy/boy-4-6-years/boy-4-6-traditional",
                          code: "CAT-5-boy-4-6-traditional-FgHzCj",
                          createdAt: "2025-08-24T13:20:42.919Z",
                          updatedAt: "2025-08-24T13:20:42.919Z",
                          __v: 0,
                        },
                      },
                      {
                        id: 2,
                        path: "/search?q=clothing/kids/boy/boy-4-6-years/boy-4-6-daily-wear",
                        label: "Daily Wear",
                        data: {
                          _id: "68ab11ab1cd8ac2fa2b71f79",
                          name: "Daily Wear",
                          slug: "boy-4-6-daily-wear",
                          parentId: "68ab11a81cd8ac2fa2b71f42",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 2,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f0b",
                              slug: "boy",
                              name: "Boy",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f42",
                              slug: "boy-4-6-years",
                              name: "4-6 Years",
                            },
                            {
                              id: "68ab11ab1cd8ac2fa2b71f79",
                              slug: "boy-4-6-daily-wear",
                              name: "Daily Wear",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/boy/boy-4-6-years/boy-4-6-daily-wear",
                          code: "CAT-5-boy-4-6-daily-wear-dv4Phv",
                          createdAt: "2025-08-24T13:20:43.118Z",
                          updatedAt: "2025-08-24T13:20:43.118Z",
                          __v: 0,
                        },
                      },
                      {
                        id: 3,
                        path: "/search?q=clothing/kids/boy/boy-4-6-years/boy-4-6-night-wear",
                        label: "Night Wear",
                        data: {
                          _id: "68ab11ab1cd8ac2fa2b71f7e",
                          name: "Night Wear",
                          slug: "boy-4-6-night-wear",
                          parentId: "68ab11a81cd8ac2fa2b71f42",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 3,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f0b",
                              slug: "boy",
                              name: "Boy",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f42",
                              slug: "boy-4-6-years",
                              name: "4-6 Years",
                            },
                            {
                              id: "68ab11ab1cd8ac2fa2b71f7e",
                              slug: "boy-4-6-night-wear",
                              name: "Night Wear",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/boy/boy-4-6-years/boy-4-6-night-wear",
                          code: "CAT-5-boy-4-6-night-wear-m-EDyX",
                          createdAt: "2025-08-24T13:20:43.298Z",
                          updatedAt: "2025-08-24T13:20:43.298Z",
                          __v: 0,
                        },
                      },
                    ],
                  },
                ],
              },
              {
                id: 2,
                path: "/search?q=clothing/kids/girl",
                label: "Girl",
                data: {
                  _id: "68ab11a61cd8ac2fa2b71f10",
                  name: "Girl",
                  slug: "girl",
                  parentId: "68ab11a21cd8ac2fa2b71ea7",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 2,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a11cd8ac2fa2b71e8c",
                      slug: "clothing",
                      name: "Clothing",
                    },
                    {
                      id: "68ab11a21cd8ac2fa2b71ea7",
                      slug: "kids",
                      name: "Kids",
                    },
                    {
                      id: "68ab11a61cd8ac2fa2b71f10",
                      slug: "girl",
                      name: "Girl",
                    },
                  ],
                  level: 3,
                  fullSlug: "clothing/kids/girl",
                  code: "CAT-3-girl-BHe8zm",
                  createdAt: "2025-08-24T13:20:38.518Z",
                  updatedAt: "2025-08-24T13:20:41.217Z",
                  __v: 0,
                },
                subItems: [
                  {
                    id: 1,
                    path: "/search?q=clothing/kids/girl/girl-0-2-years",
                    label: "0-2 Years",
                    data: {
                      _id: "68ab11a81cd8ac2fa2b71f47",
                      name: "0-2 Years",
                      slug: "girl-0-2-years",
                      parentId: "68ab11a61cd8ac2fa2b71f10",
                      isLeaf: false,
                      isActive: true,
                      displayOrder: 1,
                      attributes: [],
                      path: [
                        {
                          id: "68ab11a11cd8ac2fa2b71e8c",
                          slug: "clothing",
                          name: "Clothing",
                        },
                        {
                          id: "68ab11a21cd8ac2fa2b71ea7",
                          slug: "kids",
                          name: "Kids",
                        },
                        {
                          id: "68ab11a61cd8ac2fa2b71f10",
                          slug: "girl",
                          name: "Girl",
                        },
                        {
                          id: "68ab11a81cd8ac2fa2b71f47",
                          slug: "girl-0-2-years",
                          name: "0-2 Years",
                        },
                      ],
                      level: 4,
                      fullSlug: "clothing/kids/girl/girl-0-2-years",
                      code: "CAT-4-girl-0-2-years-cstdii",
                      createdAt: "2025-08-24T13:20:40.798Z",
                      updatedAt: "2025-08-24T13:20:43.757Z",
                      __v: 0,
                    },
                    nestedItems: [
                      {
                        id: 1,
                        path: "/search?q=clothing/kids/girl/girl-0-2-years/girl-0-2-traditional",
                        label: "Traditional",
                        data: {
                          _id: "68ab11ab1cd8ac2fa2b71f83",
                          name: "Traditional",
                          slug: "girl-0-2-traditional",
                          parentId: "68ab11a81cd8ac2fa2b71f47",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 1,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f10",
                              slug: "girl",
                              name: "Girl",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f47",
                              slug: "girl-0-2-years",
                              name: "0-2 Years",
                            },
                            {
                              id: "68ab11ab1cd8ac2fa2b71f83",
                              slug: "girl-0-2-traditional",
                              name: "Traditional",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/girl/girl-0-2-years/girl-0-2-traditional",
                          code: "CAT-5-girl-0-2-traditional-hEZMAR",
                          createdAt: "2025-08-24T13:20:43.418Z",
                          updatedAt: "2025-08-24T13:20:43.418Z",
                          __v: 0,
                        },
                      },
                      {
                        id: 2,
                        path: "/search?q=clothing/kids/girl/girl-0-2-years/girl-0-2-daily-wear",
                        label: "Daily Wear",
                        data: {
                          _id: "68ab11ab1cd8ac2fa2b71f88",
                          name: "Daily Wear",
                          slug: "girl-0-2-daily-wear",
                          parentId: "68ab11a81cd8ac2fa2b71f47",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 2,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f10",
                              slug: "girl",
                              name: "Girl",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f47",
                              slug: "girl-0-2-years",
                              name: "0-2 Years",
                            },
                            {
                              id: "68ab11ab1cd8ac2fa2b71f88",
                              slug: "girl-0-2-daily-wear",
                              name: "Daily Wear",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/girl/girl-0-2-years/girl-0-2-daily-wear",
                          code: "CAT-5-girl-0-2-daily-wear-RcFZie",
                          createdAt: "2025-08-24T13:20:43.558Z",
                          updatedAt: "2025-08-24T13:20:43.558Z",
                          __v: 0,
                        },
                      },
                      {
                        id: 3,
                        path: "/search?q=clothing/kids/girl/girl-0-2-years/girl-0-2-night-wear",
                        label: "Night Wear",
                        data: {
                          _id: "68ab11ab1cd8ac2fa2b71f8d",
                          name: "Night Wear",
                          slug: "girl-0-2-night-wear",
                          parentId: "68ab11a81cd8ac2fa2b71f47",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 3,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f10",
                              slug: "girl",
                              name: "Girl",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f47",
                              slug: "girl-0-2-years",
                              name: "0-2 Years",
                            },
                            {
                              id: "68ab11ab1cd8ac2fa2b71f8d",
                              slug: "girl-0-2-night-wear",
                              name: "Night Wear",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/girl/girl-0-2-years/girl-0-2-night-wear",
                          code: "CAT-5-girl-0-2-night-wear-6-bAjV",
                          createdAt: "2025-08-24T13:20:43.698Z",
                          updatedAt: "2025-08-24T13:20:43.698Z",
                          __v: 0,
                        },
                      },
                    ],
                  },
                  {
                    id: 2,
                    path: "/search?q=clothing/kids/girl/girl-2-4-years",
                    label: "2-4 Years",
                    data: {
                      _id: "68ab11a81cd8ac2fa2b71f4c",
                      name: "2-4 Years",
                      slug: "girl-2-4-years",
                      parentId: "68ab11a61cd8ac2fa2b71f10",
                      isLeaf: false,
                      isActive: true,
                      displayOrder: 2,
                      attributes: [],
                      path: [
                        {
                          id: "68ab11a11cd8ac2fa2b71e8c",
                          slug: "clothing",
                          name: "Clothing",
                        },
                        {
                          id: "68ab11a21cd8ac2fa2b71ea7",
                          slug: "kids",
                          name: "Kids",
                        },
                        {
                          id: "68ab11a61cd8ac2fa2b71f10",
                          slug: "girl",
                          name: "Girl",
                        },
                        {
                          id: "68ab11a81cd8ac2fa2b71f4c",
                          slug: "girl-2-4-years",
                          name: "2-4 Years",
                        },
                      ],
                      level: 4,
                      fullSlug: "clothing/kids/girl/girl-2-4-years",
                      code: "CAT-4-girl-2-4-years-UjxUDo",
                      createdAt: "2025-08-24T13:20:41.018Z",
                      updatedAt: "2025-08-24T13:20:44.157Z",
                      __v: 0,
                    },
                    nestedItems: [
                      {
                        id: 1,
                        path: "/search?q=clothing/kids/girl/girl-2-4-years/girl-2-4-traditional",
                        label: "Traditional",
                        data: {
                          _id: "68ab11ab1cd8ac2fa2b71f92",
                          name: "Traditional",
                          slug: "girl-2-4-traditional",
                          parentId: "68ab11a81cd8ac2fa2b71f4c",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 1,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f10",
                              slug: "girl",
                              name: "Girl",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f4c",
                              slug: "girl-2-4-years",
                              name: "2-4 Years",
                            },
                            {
                              id: "68ab11ab1cd8ac2fa2b71f92",
                              slug: "girl-2-4-traditional",
                              name: "Traditional",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/girl/girl-2-4-years/girl-2-4-traditional",
                          code: "CAT-5-girl-2-4-traditional-TyYgKF",
                          createdAt: "2025-08-24T13:20:43.838Z",
                          updatedAt: "2025-08-24T13:20:43.838Z",
                          __v: 0,
                        },
                      },
                      {
                        id: 2,
                        path: "/search?q=clothing/kids/girl/girl-2-4-years/girl-2-4-daily-wear",
                        label: "Daily Wear",
                        data: {
                          _id: "68ab11ab1cd8ac2fa2b71f97",
                          name: "Daily Wear",
                          slug: "girl-2-4-daily-wear",
                          parentId: "68ab11a81cd8ac2fa2b71f4c",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 2,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f10",
                              slug: "girl",
                              name: "Girl",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f4c",
                              slug: "girl-2-4-years",
                              name: "2-4 Years",
                            },
                            {
                              id: "68ab11ab1cd8ac2fa2b71f97",
                              slug: "girl-2-4-daily-wear",
                              name: "Daily Wear",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/girl/girl-2-4-years/girl-2-4-daily-wear",
                          code: "CAT-5-girl-2-4-daily-wear-yEt4Zn",
                          createdAt: "2025-08-24T13:20:43.978Z",
                          updatedAt: "2025-08-24T13:20:43.978Z",
                          __v: 0,
                        },
                      },
                      {
                        id: 3,
                        path: "/search?q=clothing/kids/girl/girl-2-4-years/girl-2-4-night-wear",
                        label: "Night Wear",
                        data: {
                          _id: "68ab11ac1cd8ac2fa2b71f9c",
                          name: "Night Wear",
                          slug: "girl-2-4-night-wear",
                          parentId: "68ab11a81cd8ac2fa2b71f4c",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 3,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f10",
                              slug: "girl",
                              name: "Girl",
                            },
                            {
                              id: "68ab11a81cd8ac2fa2b71f4c",
                              slug: "girl-2-4-years",
                              name: "2-4 Years",
                            },
                            {
                              id: "68ab11ac1cd8ac2fa2b71f9c",
                              slug: "girl-2-4-night-wear",
                              name: "Night Wear",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/girl/girl-2-4-years/girl-2-4-night-wear",
                          code: "CAT-5-girl-2-4-night-wear-FG6J7v",
                          createdAt: "2025-08-24T13:20:44.118Z",
                          updatedAt: "2025-08-24T13:20:44.118Z",
                          __v: 0,
                        },
                      },
                    ],
                  },
                  {
                    id: 3,
                    path: "/search?q=clothing/kids/girl/girl-4-6-years",
                    label: "4-6 Years",
                    data: {
                      _id: "68ab11a91cd8ac2fa2b71f51",
                      name: "4-6 Years",
                      slug: "girl-4-6-years",
                      parentId: "68ab11a61cd8ac2fa2b71f10",
                      isLeaf: false,
                      isActive: true,
                      displayOrder: 3,
                      attributes: [],
                      path: [
                        {
                          id: "68ab11a11cd8ac2fa2b71e8c",
                          slug: "clothing",
                          name: "Clothing",
                        },
                        {
                          id: "68ab11a21cd8ac2fa2b71ea7",
                          slug: "kids",
                          name: "Kids",
                        },
                        {
                          id: "68ab11a61cd8ac2fa2b71f10",
                          slug: "girl",
                          name: "Girl",
                        },
                        {
                          id: "68ab11a91cd8ac2fa2b71f51",
                          slug: "girl-4-6-years",
                          name: "4-6 Years",
                        },
                      ],
                      level: 4,
                      fullSlug: "clothing/kids/girl/girl-4-6-years",
                      code: "CAT-4-girl-4-6-years-PEWR9t",
                      createdAt: "2025-08-24T13:20:41.158Z",
                      updatedAt: "2025-08-24T13:20:44.637Z",
                      __v: 0,
                    },
                    nestedItems: [
                      {
                        id: 1,
                        path: "/search?q=clothing/kids/girl/girl-4-6-years/girl-4-6-traditional",
                        label: "Traditional",
                        data: {
                          _id: "68ab11ac1cd8ac2fa2b71fa1",
                          name: "Traditional",
                          slug: "girl-4-6-traditional",
                          parentId: "68ab11a91cd8ac2fa2b71f51",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 1,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f10",
                              slug: "girl",
                              name: "Girl",
                            },
                            {
                              id: "68ab11a91cd8ac2fa2b71f51",
                              slug: "girl-4-6-years",
                              name: "4-6 Years",
                            },
                            {
                              id: "68ab11ac1cd8ac2fa2b71fa1",
                              slug: "girl-4-6-traditional",
                              name: "Traditional",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/girl/girl-4-6-years/girl-4-6-traditional",
                          code: "CAT-5-girl-4-6-traditional-ViD9uX",
                          createdAt: "2025-08-24T13:20:44.298Z",
                          updatedAt: "2025-08-24T13:20:44.298Z",
                          __v: 0,
                        },
                      },
                      {
                        id: 2,
                        path: "/search?q=clothing/kids/girl/girl-4-6-years/girl-4-6-daily-wear",
                        label: "Daily Wear",
                        data: {
                          _id: "68ab11ac1cd8ac2fa2b71fa6",
                          name: "Daily Wear",
                          slug: "girl-4-6-daily-wear",
                          parentId: "68ab11a91cd8ac2fa2b71f51",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 2,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f10",
                              slug: "girl",
                              name: "Girl",
                            },
                            {
                              id: "68ab11a91cd8ac2fa2b71f51",
                              slug: "girl-4-6-years",
                              name: "4-6 Years",
                            },
                            {
                              id: "68ab11ac1cd8ac2fa2b71fa6",
                              slug: "girl-4-6-daily-wear",
                              name: "Daily Wear",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/girl/girl-4-6-years/girl-4-6-daily-wear",
                          code: "CAT-5-girl-4-6-daily-wear-Y40M8N",
                          createdAt: "2025-08-24T13:20:44.438Z",
                          updatedAt: "2025-08-24T13:20:44.438Z",
                          __v: 0,
                        },
                      },
                      {
                        id: 3,
                        path: "/search?q=clothing/kids/girl/girl-4-6-years/girl-4-6-night-wear",
                        label: "Night Wear",
                        data: {
                          _id: "68ab11ac1cd8ac2fa2b71fab",
                          name: "Night Wear",
                          slug: "girl-4-6-night-wear",
                          parentId: "68ab11a91cd8ac2fa2b71f51",
                          isLeaf: false,
                          isActive: true,
                          displayOrder: 3,
                          attributes: [],
                          path: [
                            {
                              id: "68ab11a11cd8ac2fa2b71e8c",
                              slug: "clothing",
                              name: "Clothing",
                            },
                            {
                              id: "68ab11a21cd8ac2fa2b71ea7",
                              slug: "kids",
                              name: "Kids",
                            },
                            {
                              id: "68ab11a61cd8ac2fa2b71f10",
                              slug: "girl",
                              name: "Girl",
                            },
                            {
                              id: "68ab11a91cd8ac2fa2b71f51",
                              slug: "girl-4-6-years",
                              name: "4-6 Years",
                            },
                            {
                              id: "68ab11ac1cd8ac2fa2b71fab",
                              slug: "girl-4-6-night-wear",
                              name: "Night Wear",
                            },
                          ],
                          level: 5,
                          fullSlug:
                            "clothing/kids/girl/girl-4-6-years/girl-4-6-night-wear",
                          code: "CAT-5-girl-4-6-night-wear-EG93Fy",
                          createdAt: "2025-08-24T13:20:44.578Z",
                          updatedAt: "2025-08-24T13:20:44.578Z",
                          __v: 0,
                        },
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 3,
    path: "/search?q=essential",
    label: "Essentials",
    data: {
      _id: "68ab11a21cd8ac2fa2b71e8f",
      name: "Essentials",
      slug: "essentials",
      parentId: null,
      isLeaf: false,
      isActive: true,
      displayOrder: 3,
      attributes: [],
      path: [
        {
          id: "68ab11a21cd8ac2fa2b71e8f",
          slug: "essential",
          name: "Essential",
        },
      ],
      level: 1,
      fullSlug: "essential",
      code: "CAT-1-essential-oIZgS7",
      createdAt: "2025-08-24T13:20:34.100Z",
      updatedAt: "2025-08-24T13:20:35.637Z",
      __v: 0,
    },
    columns: [
      {
        id: 1,
        columnItems: [
          {
            id: 1,
            path: "/search?q=essential/combos",
            label: "Combos",
            data: {
              _id: "68ab11a31cd8ac2fa2b71eac",
              name: "Combos",
              slug: "combos",
              parentId: "68ab11a21cd8ac2fa2b71e8f",
              isLeaf: false,
              isActive: true,
              displayOrder: 1,
              attributes: [],
              path: [
                {
                  id: "68ab11a21cd8ac2fa2b71e8f",
                  slug: "essential",
                  name: "Essential",
                },
                {
                  id: "68ab11a31cd8ac2fa2b71eac",
                  slug: "combos",
                  name: "Combos",
                },
              ],
              level: 2,
              fullSlug: "essential/combos",
              code: "CAT-2-combos-gz9OLf",
              createdAt: "2025-08-24T13:20:35.239Z",
              updatedAt: "2025-08-24T13:20:35.239Z",
              __v: 0,
            },
          },
        ],
      },
      {
        id: 2,
        columnItems: [
          {
            id: 2,
            path: "/search?q=essential/festival-essentials",
            label: "Festival Essentials",
            data: {
              _id: "68ab11a31cd8ac2fa2b71eb1",
              name: "Festival Essentials",
              slug: "festival-essentials",
              parentId: "68ab11a21cd8ac2fa2b71e8f",
              isLeaf: false,
              isActive: true,
              displayOrder: 2,
              attributes: [],
              path: [
                {
                  id: "68ab11a21cd8ac2fa2b71e8f",
                  slug: "essential",
                  name: "Essential",
                },
                {
                  id: "68ab11a31cd8ac2fa2b71eb1",
                  slug: "festival-essentials",
                  name: "Festival Essentials",
                },
              ],
              level: 2,
              fullSlug: "essential/festival-essentials",
              code: "CAT-2-festival-essentials-EzFwK_",
              createdAt: "2025-08-24T13:20:35.419Z",
              updatedAt: "2025-08-24T13:20:38.837Z",
              __v: 0,
            },
            columnItemItems: [
              {
                id: 1,
                path: "/search?q=essential/festival-essentials/pooja-essentials",
                label: "Pooja Essentials",
                data: {
                  _id: "68ab11a61cd8ac2fa2b71f15",
                  name: "Pooja Essentials",
                  slug: "pooja-essentials",
                  parentId: "68ab11a31cd8ac2fa2b71eb1",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 1,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a21cd8ac2fa2b71e8f",
                      slug: "essential",
                      name: "Essential",
                    },
                    {
                      id: "68ab11a31cd8ac2fa2b71eb1",
                      slug: "festival-essentials",
                      name: "Festival Essentials",
                    },
                    {
                      id: "68ab11a61cd8ac2fa2b71f15",
                      slug: "pooja-essentials",
                      name: "Pooja Essentials",
                    },
                  ],
                  level: 3,
                  fullSlug: "essential/festival-essentials/pooja-essentials",
                  code: "CAT-3-pooja-essentials-7V6X-I",
                  createdAt: "2025-08-24T13:20:38.658Z",
                  updatedAt: "2025-08-24T13:20:38.658Z",
                  __v: 0,
                },
              },
              {
                id: 2,
                path: "/search?q=essential/festival-essentials/festival-decoration-essentials",
                label: "Decoration Essentials",
                data: {
                  _id: "68ab11a61cd8ac2fa2b71f1a",
                  name: "Decoration Essentials",
                  slug: "festival-decoration-essentials",
                  parentId: "68ab11a31cd8ac2fa2b71eb1",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 2,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a21cd8ac2fa2b71e8f",
                      slug: "essential",
                      name: "Essential",
                    },
                    {
                      id: "68ab11a31cd8ac2fa2b71eb1",
                      slug: "festival-essentials",
                      name: "Festival Essentials",
                    },
                    {
                      id: "68ab11a61cd8ac2fa2b71f1a",
                      slug: "festival-decoration-essentials",
                      name: "Decoration Essentials",
                    },
                  ],
                  level: 3,
                  fullSlug:
                    "essential/festival-essentials/festival-decoration-essentials",
                  code: "CAT-3-festival-decoration-essentials-2Nawps",
                  createdAt: "2025-08-24T13:20:38.798Z",
                  updatedAt: "2025-08-24T13:20:38.798Z",
                  __v: 0,
                },
              },
            ],
          },
        ],
      },
      {
        id: 3,
        columnItems: [
          {
            id: 3,
            path: "/search?q=essential/celebration-essentials",
            label: "Celebration Essentials",
            data: {
              _id: "68ab11a31cd8ac2fa2b71eb6",
              name: "Celebration Essentials",
              slug: "celebration-essentials",
              parentId: "68ab11a21cd8ac2fa2b71e8f",
              isLeaf: false,
              isActive: true,
              displayOrder: 3,
              attributes: [],
              path: [
                {
                  id: "68ab11a21cd8ac2fa2b71e8f",
                  slug: "essential",
                  name: "Essential",
                },
                {
                  id: "68ab11a31cd8ac2fa2b71eb6",
                  slug: "celebration-essentials",
                  name: "Celebration Essentials",
                },
              ],
              level: 2,
              fullSlug: "essential/celebration-essentials",
              code: "CAT-2-celebration-essentials-JUVrBF",
              createdAt: "2025-08-24T13:20:35.579Z",
              updatedAt: "2025-08-24T13:20:40.117Z",
              __v: 0,
            },
            columnItemItems: [
              {
                id: 1,
                path: "/search?q=essential/celebration-essentials/party-essentials",
                label: "Party Essentials",
                data: {
                  _id: "68ab11a61cd8ac2fa2b71f1f",
                  name: "Party Essentials",
                  slug: "party-essentials",
                  parentId: "68ab11a31cd8ac2fa2b71eb6",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 1,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a21cd8ac2fa2b71e8f",
                      slug: "essential",
                      name: "Essential",
                    },
                    {
                      id: "68ab11a31cd8ac2fa2b71eb6",
                      slug: "celebration-essentials",
                      name: "Celebration Essentials",
                    },
                    {
                      id: "68ab11a61cd8ac2fa2b71f1f",
                      slug: "party-essentials",
                      name: "Party Essentials",
                    },
                  ],
                  level: 3,
                  fullSlug: "essential/celebration-essentials/party-essentials",
                  code: "CAT-3-party-essentials-isBCyP",
                  createdAt: "2025-08-24T13:20:38.938Z",
                  updatedAt: "2025-08-24T13:20:38.938Z",
                  __v: 0,
                },
              },
              {
                id: 2,
                path: "/search?q=essential/celebration-essentials/celebration-decoration-essentials",
                label: "Decoration Essentials",
                data: {
                  _id: "68ab11a71cd8ac2fa2b71f24",
                  name: "Decoration Essentials",
                  slug: "celebration-decoration-essentials",
                  parentId: "68ab11a31cd8ac2fa2b71eb6",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 2,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a21cd8ac2fa2b71e8f",
                      slug: "essential",
                      name: "Essential",
                    },
                    {
                      id: "68ab11a31cd8ac2fa2b71eb6",
                      slug: "celebration-essentials",
                      name: "Celebration Essentials",
                    },
                    {
                      id: "68ab11a71cd8ac2fa2b71f24",
                      slug: "celebration-decoration-essentials",
                      name: "Decoration Essentials",
                    },
                  ],
                  level: 3,
                  fullSlug:
                    "essential/celebration-essentials/celebration-decoration-essentials",
                  code: "CAT-3-celebration-decoration-essentials-Y-hMlW",
                  createdAt: "2025-08-24T13:20:39.138Z",
                  updatedAt: "2025-08-24T13:20:39.138Z",
                  __v: 0,
                },
              },
              {
                id: 3,
                path: "/search?q=essential/celebration-essentials/birthday",
                label: "Birthday",
                data: {
                  _id: "68ab11a71cd8ac2fa2b71f29",
                  name: "Birthday",
                  slug: "birthday",
                  parentId: "68ab11a31cd8ac2fa2b71eb6",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 3,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a21cd8ac2fa2b71e8f",
                      slug: "essential",
                      name: "Essential",
                    },
                    {
                      id: "68ab11a31cd8ac2fa2b71eb6",
                      slug: "celebration-essentials",
                      name: "Celebration Essentials",
                    },
                    {
                      id: "68ab11a71cd8ac2fa2b71f29",
                      slug: "birthday",
                      name: "Birthday",
                    },
                  ],
                  level: 3,
                  fullSlug: "essential/celebration-essentials/birthday",
                  code: "CAT-3-birthday-dMpgD8",
                  createdAt: "2025-08-24T13:20:39.518Z",
                  updatedAt: "2025-08-24T13:20:39.518Z",
                  __v: 0,
                },
              },
              {
                id: 4,
                path: "/search?q=essential/celebration-essentials/marriage",
                label: "Marriage",
                data: {
                  _id: "68ab11a71cd8ac2fa2b71f2e",
                  name: "Marriage",
                  slug: "marriage",
                  parentId: "68ab11a31cd8ac2fa2b71eb6",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 4,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a21cd8ac2fa2b71e8f",
                      slug: "essential",
                      name: "Essential",
                    },
                    {
                      id: "68ab11a31cd8ac2fa2b71eb6",
                      slug: "celebration-essentials",
                      name: "Celebration Essentials",
                    },
                    {
                      id: "68ab11a71cd8ac2fa2b71f2e",
                      slug: "marriage",
                      name: "Marriage",
                    },
                  ],
                  level: 3,
                  fullSlug: "essential/celebration-essentials/marriage",
                  code: "CAT-3-marriage-dEOU0E",
                  createdAt: "2025-08-24T13:20:39.858Z",
                  updatedAt: "2025-08-24T13:20:39.858Z",
                  __v: 0,
                },
              },
              {
                id: 5,
                path: "/search?q=essential/celebration-essentials/anniversary",
                label: "Anniversary",
                data: {
                  _id: "68ab11a81cd8ac2fa2b71f33",
                  name: "Anniversary",
                  slug: "anniversary",
                  parentId: "68ab11a31cd8ac2fa2b71eb6",
                  isLeaf: false,
                  isActive: true,
                  displayOrder: 5,
                  attributes: [],
                  path: [
                    {
                      id: "68ab11a21cd8ac2fa2b71e8f",
                      slug: "essential",
                      name: "Essential",
                    },
                    {
                      id: "68ab11a31cd8ac2fa2b71eb6",
                      slug: "celebration-essentials",
                      name: "Celebration Essentials",
                    },
                    {
                      id: "68ab11a81cd8ac2fa2b71f33",
                      slug: "anniversary",
                      name: "Anniversary",
                    },
                  ],
                  level: 3,
                  fullSlug: "essential/celebration-essentials/anniversary",
                  code: "CAT-3-anniversary-AFqkaG",
                  createdAt: "2025-08-24T13:20:40.078Z",
                  updatedAt: "2025-08-24T13:20:40.078Z",
                  __v: 0,
                },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 4,
    path: "/search?q=purohits",
    label: "Purohits",
    data: {
      _id: "68ab11a21cd8ac2fa2b71e92",
      name: "Purohits",
      slug: "purohits\n",
      parentId: null,
      isLeaf: false,
      isActive: true,
      displayOrder: 4,
      attributes: [],
      path: [
        {
          id: "68ab11a21cd8ac2fa2b71e92",
          slug: "purohit",
          name: "Purohit",
        },
      ],
      level: 1,
      fullSlug: "purohits",
      code: "CAT-1-purohit-uKXTPx",
      createdAt: "2025-08-24T13:20:34.179Z",
      updatedAt: "2025-08-24T13:20:34.179Z",
      __v: 0,
    },
    columns: [],
  },
  {
    id: 5,
    path: "/search?q=food",
    label: "Food",
    data: {
      _id: "68ab11a21cd8ac2fa2b71e95",
      name: "Food",
      slug: "food",
      parentId: null,
      isLeaf: false,
      isActive: true,
      displayOrder: 5,
      attributes: [],
      path: [
        {
          id: "68ab11a21cd8ac2fa2b71e95",
          slug: "food",
          name: "Food",
        },
      ],
      level: 1,
      fullSlug: "food",
      code: "CAT-1-food-nkm8gK",
      createdAt: "2025-08-24T13:20:34.259Z",
      updatedAt: "2025-08-24T13:20:36.078Z",
      __v: 0,
    },
    columns: [
      {
        id: 1,
        columnItems: [
          {
            id: 1,
            path: "/search?q=food/buffet",
            label: "Buffet",
            data: {
              _id: "68ab11a31cd8ac2fa2b71ebb",
              name: "Buffet",
              slug: "buffet",
              parentId: "68ab11a21cd8ac2fa2b71e95",
              isLeaf: false,
              isActive: true,
              displayOrder: 1,
              attributes: [],
              path: [
                {
                  id: "68ab11a21cd8ac2fa2b71e95",
                  slug: "food",
                  name: "Food",
                },
                {
                  id: "68ab11a31cd8ac2fa2b71ebb",
                  slug: "buffet",
                  name: "Buffet",
                },
              ],
              level: 2,
              fullSlug: "food/buffet",
              code: "CAT-2-buffet-fFNogI",
              createdAt: "2025-08-24T13:20:35.758Z",
              updatedAt: "2025-08-24T13:20:35.758Z",
              __v: 0,
            },
          },
        ],
      },
      {
        id: 2,
        columnItems: [
          {
            id: 2,
            path: "/search?q=food/organic-pickels",
            label: "Organic Pickels",
            data: {
              _id: "68ab11a31cd8ac2fa2b71ec0",
              name: "Organic Pickels",
              slug: "organic-pickels",
              parentId: "68ab11a21cd8ac2fa2b71e95",
              isLeaf: false,
              isActive: true,
              displayOrder: 2,
              attributes: [],
              path: [
                {
                  id: "68ab11a21cd8ac2fa2b71e95",
                  slug: "food",
                  name: "Food",
                },
                {
                  id: "68ab11a31cd8ac2fa2b71ec0",
                  slug: "organic-pickels",
                  name: "Organic Pickels",
                },
              ],
              level: 2,
              fullSlug: "food/organic-pickels",
              code: "CAT-2-organic-pickels-0yhHbJ",
              createdAt: "2025-08-24T13:20:35.898Z",
              updatedAt: "2025-08-24T13:20:35.898Z",
              __v: 0,
            },
          },
        ],
      },
      {
        id: 3,
        columnItems: [
          {
            id: 3,
            path: "/search?q=food/festival-specials",
            label: "Festival Specials",
            data: {
              _id: "68ab11a31cd8ac2fa2b71ec5",
              name: "Festival Specials",
              slug: "festival-specials",
              parentId: "68ab11a21cd8ac2fa2b71e95",
              isLeaf: false,
              isActive: true,
              displayOrder: 3,
              attributes: [],
              path: [
                {
                  id: "68ab11a21cd8ac2fa2b71e95",
                  slug: "food",
                  name: "Food",
                },
                {
                  id: "68ab11a31cd8ac2fa2b71ec5",
                  slug: "festival-specials",
                  name: "Festival Specials",
                },
              ],
              level: 2,
              fullSlug: "food/festival-specials",
              code: "CAT-2-festival-specials-V2O2Fo",
              createdAt: "2025-08-24T13:20:36.038Z",
              updatedAt: "2025-08-24T13:20:36.038Z",
              __v: 0,
            },
          },
        ],
      },
    ],
  },
  {
    id: 6,
    path: "/search?q=gifting",
    label: "Gifting",
    data: {
      _id: "68ab11a21cd8ac2fa2b71e97",
      name: "Gifting",
      slug: "gifting",
      parentId: null,
      isLeaf: false,
      isActive: true,
      displayOrder: 6,
      attributes: [],
      path: [
        {
          id: "68ab11a21cd8ac2fa2b71e97",
          slug: "gifting",
          name: "Gifting",
        },
      ],
      level: 1,
      fullSlug: "gifting",
      code: "CAT-1-gifting-6QPt_t",
      createdAt: "2025-08-24T13:20:34.319Z",
      updatedAt: "2025-08-24T13:20:36.537Z",
      __v: 0,
    },
    columns: [
      {
        id: 1,
        columnItems: [
          {
            id: 1,
            path: "/search?q=gifting/customised-gifting",
            label: "Customised Gifting",
            data: {
              _id: "68ab11a41cd8ac2fa2b71eca",
              name: "Customised Gifting",
              slug: "customised-gifting",
              parentId: "68ab11a21cd8ac2fa2b71e97",
              isLeaf: false,
              isActive: true,
              displayOrder: 1,
              attributes: [],
              path: [
                {
                  id: "68ab11a21cd8ac2fa2b71e97",
                  slug: "gifting",
                  name: "Gifting",
                },
                {
                  id: "68ab11a41cd8ac2fa2b71eca",
                  slug: "customised-gifting",
                  name: "Customised Gifting",
                },
              ],
              level: 2,
              fullSlug: "gifting/customised-gifting",
              code: "CAT-2-customised-gifting-QPqhxj",
              createdAt: "2025-08-24T13:20:36.198Z",
              updatedAt: "2025-08-24T13:20:36.198Z",
              __v: 0,
            },
          },
        ],
      },
      {
        id: 2,
        columnItems: [
          {
            id: 2,
            path: "/search?q=gifting/corporate-gifting",
            label: "Corporate Gifting",
            data: {
              _id: "68ab11a41cd8ac2fa2b71ecf",
              name: "Corporate Gifting",
              slug: "corporate-gifting",
              parentId: "68ab11a21cd8ac2fa2b71e97",
              isLeaf: false,
              isActive: true,
              displayOrder: 2,
              attributes: [],
              path: [
                {
                  id: "68ab11a21cd8ac2fa2b71e97",
                  slug: "gifting",
                  name: "Gifting",
                },
                {
                  id: "68ab11a41cd8ac2fa2b71ecf",
                  slug: "corporate-gifting",
                  name: "Corporate Gifting",
                },
              ],
              level: 2,
              fullSlug: "gifting/corporate-gifting",
              code: "CAT-2-corporate-gifting-CAE5IE",
              createdAt: "2025-08-24T13:20:36.338Z",
              updatedAt: "2025-08-24T13:20:36.338Z",
              __v: 0,
            },
          },
        ],
      },
      {
        id: 3,
        columnItems: [
          {
            id: 3,
            path: "/search?q=gifting/cakes",
            label: "Cakes",
            data: {
              _id: "68ab11a41cd8ac2fa2b71ed4",
              name: "Cakes",
              slug: "cakes",
              parentId: "68ab11a21cd8ac2fa2b71e97",
              isLeaf: false,
              isActive: true,
              displayOrder: 3,
              attributes: [],
              path: [
                {
                  id: "68ab11a21cd8ac2fa2b71e97",
                  slug: "gifting",
                  name: "Gifting",
                },
                {
                  id: "68ab11a41cd8ac2fa2b71ed4",
                  slug: "cakes",
                  name: "Cakes",
                },
              ],
              level: 2,
              fullSlug: "gifting/cakes",
              code: "CAT-2-cakes-tnPcnx",
              createdAt: "2025-08-24T13:20:36.498Z",
              updatedAt: "2025-08-24T13:20:36.498Z",
              __v: 0,
            },
          },
        ],
      },
    ],
  },
];
